import assert from "node:assert/strict";
import test from "node:test";
import { MAGIC_CONTEXT_AGENTS, classifyMessageMetadata, classifySessionMetadata, coerceScopeEvidence, createScopeRegistry, isMeasurementScopeEligible, isSessionScopeExcluded } from "../src/scope.js";

test("exact hidden IDs classify session, assistant agent and guaranteed v1 mode", () => {
  for (const id of MAGIC_CONTEXT_AGENTS) {
    assert.equal(classifySessionMetadata({ agent: id }).sourceScope, "magic-session");
    assert.equal(classifyMessageMetadata({ role: "assistant", agent: id }).sourceScope, "magic-session");
    assert.equal(classifyMessageMetadata({ role: "assistant", mode: id }).sourceScope, "magic-session");
    assert.equal(classifyMessageMetadata({ role: "assistant", mode: id, modelID: "magic-context" }).sourceScope, "magic-session");
  }
  for (const id of ["editor", "custom-editor", "dreamer-custom", "my-historian"]) {
    assert.equal(classifySessionMetadata({ agent: id }).sourceScope, "user");
    assert.equal(classifyMessageMetadata({ mode: id }).sourceScope, "user");
  }
  assert.equal(classifyMessageMetadata({ role: "user", agent: "dreamer" }).sourceScope, "pending");
});

test("session metadata and legacy/new titles require exact positive evidence", () => {
  for (const role of [undefined, "historian", "dreamer", "dreamer-curate"]) {
    assert.equal(classifySessionMetadata({ metadata: { magic_context: "hidden-run", role } }).sourceScope, "magic-session");
  }
  for (const metadata of [{ magic_context: "hidden-run", role: "editor" }, { magic_context: "other", role: "dreamer" }]) {
    assert.equal(classifySessionMetadata({ metadata }).sourceScope, "pending");
  }
  for (const title of ["magic-context-anything", "Magic Context historian", "Magic Context dreamer"]) {
    assert.equal(classifySessionMetadata({ title }).sourceScope, "magic-session");
  }
  for (const title of ["Discuss Magic Context", "Magic Context historian extra", "MAGIC-CONTEXT-test", "A magic-context-test"]) {
    assert.equal(classifySessionMetadata({ title, modelID: "dreamer" }).sourceScope, "pending");
  }
});

test("compaction excludes only a message, never its user session or children", () => {
  const registry = createScopeRegistry();
  registry.observeSessionMetadata("user", { agent: "build" });
  registry.observeSessionMetadata("child", { parentID: "user" });
  for (const message of [{ modelID: "magic-context" }, { providerID: "magic-context" }, { summary: true, mode: "compaction" }, { agent: "compaction" }]) {
    const before = registry.revision;
    const scope = registry.observeMessageMetadata("user", { role: "assistant", ...message });
    assert.equal(scope.sourceScope, "magic-message");
    assert.equal(registry.getScope("user"), "user");
    assert.equal(registry.isExcluded("child"), false);
    assert.equal(registry.revision, before);
    assert.equal(isMeasurementScopeEligible({ sessionID: "user", scope }, registry.serialize()), false);
  }
  assert.equal(classifyMessageMetadata({ summary: false, mode: "compaction" }).sourceScope, "user");
  assert.equal(classifyMessageMetadata({ summary: true, mode: "build" }).sourceScope, "user");
  assert.equal(classifyMessageMetadata({ modelID: "provider/magic-context" }).sourceScope, "pending");
});

test("late assistant identity is sticky, inherited cycle-safely and serialized for restart", () => {
  const registry = createScopeRegistry();
  registry.observeSessionMetadata("mc", { title: "Autogenerated child", parentID: "user" });
  registry.observeSessionMetadata("child", { parentID: "mc" });
  registry.observeSessionMetadata("grand", { parentID: "child" });
  registry.observeSessionMetadata("real", { parentID: "user", agent: "editor" });
  assert.equal(registry.getScope("mc"), "pending");
  const before = registry.revision;
  registry.observeMessageMetadata("mc", { mode: "historian-editor" });
  assert.ok(registry.revision > before);
  assert.equal(registry.getScope("grand"), "magic-session");
  assert.equal(registry.getScope("user"), "pending");
  assert.equal(registry.getScope("real"), "user");
  const stable = registry.revision;
  registry.observeMessageMetadata("mc", { mode: "historian-editor" });
  assert.equal(registry.revision, stable);
  registry.observeSessionMetadata("mc", { agent: "editor", title: "new normal-looking title" });
  assert.equal(registry.isExcluded("mc"), true);
  const serialized = JSON.stringify(registry.serialize());
  assert.equal(serialized.includes("title"), false);
  assert.equal(serialized.includes("Autogenerated"), false);
  const restarted = createScopeRegistry(JSON.parse(serialized));
  assert.equal(restarted.isExcluded("grand"), true);
  assert.equal(restarted.isExcluded("real"), false);
  const cycle = { a: "b", b: "a" };
  assert.equal(isSessionScopeExcluded("a", {}, cycle), false);
  assert.equal(isSessionScopeExcluded("a", { b: classifyMessageMetadata({ mode: "dreamer" }) }, cycle), true);
});

test("absent or failed/404 metadata never drops a normal user; transient cache is bounded", () => {
  const registry = createScopeRegistry({}, 2);
  registry.observeSessionMetadata("user", { agent: "build" });
  registry.observeSessionMetadata("user", undefined);
  registry.observeSessionMetadata("user", { status: 404 });
  assert.equal(registry.getScope("user"), "user");
  registry.observeMessageMetadata("positive", { mode: "dreamer" });
  for (let index = 0; index < 20; index++) registry.observeSessionMetadata(`unknown-${index}`, {});
  assert.equal(registry.getEvidence("unknown-0"), undefined);
  assert.equal(registry.isExcluded("user"), false);
  assert.equal(registry.isExcluded("positive"), true);
  assert.deepEqual(Object.keys(registry.serialize()), ["positive"]);
  const compact = coerceScopeEvidence({ version: 1, sourceScope: "magic-session", reasons: ["message-mode", "message-mode", "secret full text"], title: "secret" });
  assert.deepEqual(compact?.reasons, ["message-mode"]);
  assert.equal(JSON.stringify(compact).includes("secret"), false);
});
